name: Read Env Variables from file
description: Reads environment variables from a passed .env file.
author: @Mulpeter91

inputs:
  filePath:
    required: true
    description: "File path to variable file."
    default: ./.github/variables*

runs:
  using: "composite"
  steps:
    - run: Get-Content ${{ inputs.filePath }} >> $GITHUB_ENV
      shell: pwsh