name: Read Env Variables from file
description: Reads environment variables from a passed .env file.
author: Robert Mulpeter @Mulpeter91

inputs:
  filePath:
    required: true
    description: "File path to variable file."
    default: ./.github/variables*

runs:
  using: "composite"
  steps:
    - run: |
        echo ${{ inputs.filePath }} >> $Env:GITHUB_ENV
        echo $Env:DOJO
      shell: pwsh