name: Read Env Variables from file
description: Reads environment variables from a passed .env file.
author: Robert Mulpeter

inputs:
  filePath:
    required: true
    description: "File path to variable file."
    default: ./.github/variables*

runs:
  using: "composite"
  steps:
    - run: |
        Write-Host "Reached"
        Write-Open ${{ inputs.filePath }} >> $GITHUB_ENV
      shell: pwsh