name: Workflow 1 - Run powershell script        # <- Optional workflow name.

on:                                             # <- The trigger definition block.
  push:                                         # <- An event to trigger the action, of type push.
    branches: [                                 # <- Target Branches. Accepts an array.
      main,
      trigger-action                            # <- Adding an empty test branch.
    ]

jobs:                                           # <- The execution of work block.
  Job-Identifier:                               # <- Required Job ID. Contains related action steps.
    name: Executing Hello World Script          # <- Optional Job Name.
    runs-on: windows-latest                     # <- Tells the server which OS to run on. Can also be windows, macOS, or even self-hosted.      
    
    steps:                                      # <- Step definitions.
      - uses: actions/checkout@v2               # <- Use keyword selects an action. Actions/ path in github is where common actions are predefined.
      - name: Printing Hello World              # <- Optional step name.
        run: ./Powershell/HelloWorld.ps1        # <- Run keyword executes a command. In this case a powershell script.