name: Workflow 2 - Access Github Environment Variables

on:
  push:
    branches: [
        main,
        trigger-action
    ]

jobs:
  Job-Identifier-Sample:
    name: Printing Github Environment Variables
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2               
      - name: Printing Environment Variables
        shell: pwsh
        run: ./Powershell/GithubEnvVariables.ps1