name: Workflow 3 - Calling a Composite Action

on:
  push:
    branches: [
        main,
        trigger-action
    ]

jobs:
  Job-Identifier-Sample:
    name: Print message from another action
    runs-on: windows-latest
    
    steps:
      - name: Print from action
        uses: ./.github/actions
