name: Workflow 3 - Passing Variables

on:
  push:
    branches: [
        main,
        trigger-action
    ]

env:
  BEST_PINT: Guinness

jobs:
  Job-Identifier-Sample:
    name: Printing Github Environment Variables
    runs-on: ubuntu-latest
    env:
      BEST_WHISKEY: Midleton   
    
    steps:
      - name: Read from File
        run: |
          Import-Module .\Powershell\Response.ps1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh   
        
      - uses: actions/checkout@v2
      - name: Printing Environment Variables
        shell: pwsh
        run: ./Powershell/PassingVariables.ps1
        env:
          BEST_COCKTAIL: Whiskey Sour