name: Workflow 3 - External Actions and Variables

on:
  push:
    branches: [
        main,
        trigger-action
    ]

jobs:
  Job-Identifier-Sample:
    name: Obtaining variables from .env file
    runs-on: windows-latest  
    
    steps:
      - name: Print Variables from .env file
        uses: ./.github/actions/obtainVariables
        with:
          varFilePath: ./.github/variables/Variables.env
        run: env