name: Workflow 3 - Passing Around Variables

on:
  push:
    branches: [
        main,
        trigger-action
    ]

env:
  BEST_PINT: Guinness

jobs:
  Job-Identifier-Sample:
    name: Printing Github Environment Variables
    runs-on: ubuntu-latest
    env:
      BEST_WHISKEY: Midleton
    
    steps:
      - uses: actions/checkout@v2
      - name: Print Variables to Script
        shell: pwsh
        run: ./Powershell/GithubEnvVariables.ps1
        env:
          BEST_COCKTAIL: Whiskey Sour

      - name: Inspect Environment Variables
        run: env