name: 4 - Passing Variables

on:
  push:
    branches: [
        main,
        trigger-action
    ]

jobs:
  Job-Identifier-Sample:
    name: Obtaining variables from .env file
    runs-on: windows-latest  
    
    steps:
      - name: Print Variables from .env file
        uses: ./.github/actions/obtainVariables@main
        with:
          varFilePath: ./.github/variables/Variables.env
          
      - name: Inspect Environment Variables
        run: env