name: 4 - Passing Variables

on:
  push:
    branches: [
        main,
        trigger-action
    ]

jobs:
  Run-Composite-Action:
    name: Print message from another action
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use print message composite action
        uses: ./.github/actions/print-message
        with:
          message: "Cobra Kai never dies"
          
      - name: Obtain Environment Variables from file
        uses: ./.github/actions/read-env-file
        with:
          filePath: ./.github/variables/variables.env