name: 2 - Access Github Environment Variables

on:
  push:
    branches: [
        main,
        another-branch
    ]
  pull_request:                                   # <- Pull request trigger.
    branches: [
        main,                                     # <- If any PR is made to branch 'main'.
        releases/**                               # <- Any branch that starts with release/.       
    ]

env:
  BEST_PINT: Guinness                             # <- Custom Env variables are set within the workflow file.
                                                  # <- High order variables are scoped to everything within the workflow.

jobs:
  Job-Identifier-Sample:
    name: Printing Github Environment Variables
    runs-on: windows-latest
    env:
      BEST_WHISKEY: Midleton                      # <- Scoped to this job and subsequent steps.         
    
    steps:  
      - uses: actions/checkout@v2   
        
      - name: Print Variables to Script
        run: ./Powershell/GithubEnvVariables.ps1
        env:
          BEST_COCKTAIL: Whiskey Sour              # <- Scoped to this step only.
          
      - name: Inspect Environment Variables
        run: env                                   # <- Prints to output the available variables to this step.
  
  Pull-Request-Variables:
    name: Obtain variables useful to a pull request
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Relevant Variables              # <- Use a pipe on line one of the run to initiate a multi-line command.
        run: |
          Write-Host "Actor to initiate workflow: ${{ $Env:GITHUB_ACTOR }}"