name: 2 - Access Github Environment Variables

on:
  push:
    branches: [
        main,
        another-branch
    ]
    
env:
  BEST_PINT: Guinness                             # <- Custom Env variables are set within the workflow file.
                                                  # <- High order variables are scoped to everything within the workflow.

jobs:
  Job-Identifier-Sample:
    name: Printing Github Environment Variables
    runs-on: windows-latest
    env:
      BEST_WHISKEY: Midleton                      # <- Scoped to this job and subsequent steps.         
    
    steps:  
      - uses: actions/checkout@v2   
        
      - name: Print Variables to Script
        run: ./Powershell/GithubEnvVariables.ps1
        env:
          BEST_COCKTAIL: Whiskey Sour              # <- Scoped to this step only.
          
      - name: Inspect Environment Variables
        run: env                                   # <- Prints to output the available variables to this step. 