name: 2 - Access Github Environment Variables

on:
  push:
    branches: [
        main,
        another-branch
    ]
  pull_request:                                   # <- Pull request trigger.
    branches: [
        main                                      # <- If any pull request is made to branch 'main'.      
    ]

env:
  BEST_PINT: Guinness                             # <- Custom Env variables are set within the workflow file.
                                                  # <- High order variables are scoped to everything within the workflow.

jobs:
  #Example 2.1
  Access-Environment-Variables:
    name: Print Github Environment Variables
    runs-on: windows-latest
    env:
      BEST_WHISKEY: Midleton                      # <- Scoped to this job and subsequent steps.         
    
    steps:  
      - uses: actions/checkout@v2   
        
      - name: Print Variables to Script
        run: ./Powershell/GithubEnvVariables.ps1
        env:
          BEST_COCKTAIL: Whiskey Sour              # <- Scoped to this step only.
          
      - name: Inspect Environment Variables
        run: env                                   # <- Prints to output the available variables to this step.
  
  Other-Environment-Variables:
    name: Print Niche Environment Variables
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      #Example 2.2
      - name: Print Variables for Pull Request     # <- Add a pipe key on the run command to include multiple commands.
        run: |
          Write-Host "Actor: $Env:GITHUB_ACTOR"
          Write-Host "Target Branch: $Env:GITHUB_BASE_REF"
          Write-Host "Source Branch: $Env:GITHUB_HEAD_REF"
       
      #Example 2.3   
      - name: Print Json from Action Event File
        run: ./Powershell/GithubEventFile.ps1
          