name: 4 - Setting & Passing Variables

on:
  push:
    branches: [
        main,
        another-branch
    ]

jobs:
  create-variables:
    name: Creating and passing variables
    runs-on: windows-latest 
    
    steps:
      #Example 4.1
      - uses: actions/checkout@v2
      
      - name: Use print message composite action
        uses: ./.github/actions/print-message
        with:                                                     # <- With keyword to signify parameters
          message: "Cobra Kai never dies"                         # <- Named parameter in the called action.
          
      #Example 4.2
      - name: Set variables from environment file
        uses: ./.github/actions/read-env-file
        with:
          filePath: ./.github/variables/variables.env

      #Example 4.3
      - name: Set variables from powershell file
        run: Get-Content ./Powershell/Variables.ps1 >> $Env:GITHUB_ENV
        
      #Example 4.4
      - name: Set local step variable to environment variable
        run: |
          echo "WORKFLOW_VARIABLE=$(echo ${LOCAL_VARIABLE})" >> $Env:GITHUB_ENV
        env:
          LOCAL_VARIABLE: Karate Kid
        
      - name: Inspect Environment Variables
        run: env 

        
  Obtain-Variables:
    needs: [Create-Variables]       # <- Jobs run concurrently by default. The 'needs' keyword sets dependant jobs.
    name: Reading previous variables
    runs-on: windows-latest    
    
    steps:
      - name: Inspect Environment Variables
        run: env